[package]
name = "bscoin"
version = "0.1.0"
authors = ["Justin Harrison <me@justinharrison.ca>"]

[dependencies]
byteorder = "1.0"
openssl = "0.9"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
time = "0.1"
